version: "3.8"

services:
  app:
    depends_on:
      - db
    build:
      dockerfile: AppDockerfile
    env_file:
      - app.env
    ports:
      - "5050:80"
    environment:
      - NGINX_PORT=80
  db:
    build:
      dockerfile: DbDockerfile
    env_file:
      - postgres.env
    volumes:
      - "/root/data/postgres:/var/lib/postgresql/data"
