version: "3.8"

services:
  web:
    depends_on:
      - api
    build:
      dockerfile: ClientDockerfile
    ports:
      - "5050:80"
    environment:
      - NGINX_PORT=80
  api:
    depends_on:
      - db
    build:
      dockerfile: ServerDockerfile
    ports: 
      - "3000:80"
  db:
    build:
      dockerfile: DbDockerfile
    env_file:
      - postgres.env
    volumes:
      - "/root/data/postgres:/var/lib/postgresql/data"
