version: "3.8"

services:
  app:
    depends_on:
      - db
    build:
      dockerfile: AppDockerfile
      args:
        - Recaptcha_Site_Key=$Recaptcha_Site_Key
    env_file:
      - app.env
    ports:
      - "$App_Port:80"
  db:
    image: postgres
    env_file:
      - postgres.env
    volumes:
      - "/root/data/postgres:/var/lib/postgresql/data"
